# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LabWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MainWindow import *

class Ui_Lab_measurement(object):
    def setupUi_lab(self, Lab_measurement):
        Lab_measurement.setObjectName("Lab_measurement")
        Lab_measurement.resize(800, 500)
        Lab_measurement.setStyleSheet("background-color: rgb(181, 181, 181);")

        self.Lab_Intro = QtWidgets.QTextBrowser(Lab_measurement)
        self.Lab_Intro.setGeometry(QtCore.QRect(30, 20, 740, 120))
        self.Lab_Intro.setObjectName("Lab_Intro")

        self.choise_text = QtWidgets.QTextBrowser(Lab_measurement)
        self.choise_text.setGeometry(QtCore.QRect(30, 160, 350, 50))
        self.choise_text.setObjectName("choise_text")

        self.GKH_btn = QtWidgets.QPushButton(Lab_measurement)
        self.GKH_btn.setGeometry(QtCore.QRect(30, 250, 320, 190))
        self.GKH_btn.setMinimumSize(QtCore.QSize(0, 190))
        self.GKH_btn.setIconSize(QtCore.QSize(50, 50))
        self.GKH_btn.setObjectName("GKH_btn")

        self.tilte_btn = QtWidgets.QPushButton(Lab_measurement)
        self.tilte_btn.setGeometry(QtCore.QRect(430, 250, 320, 190))
        self.tilte_btn.setMinimumSize(QtCore.QSize(0, 190))
        self.tilte_btn.setIconSize(QtCore.QSize(50, 50))
        self.tilte_btn.setObjectName("GKH_btn_2")

        self.Back_btn = QtWidgets.QPushButton(Lab_measurement)
        self.Back_btn.setGeometry(QtCore.QRect(570, 160, 170, 50))
        self.Back_btn.setObjectName("Back_btn")
        self.Back_btn.clicked.connect(self.back_action)

        self.retranslateUi(Lab_measurement)
        QtCore.QMetaObject.connectSlotsByName(Lab_measurement)

    def retranslateUi(self, Lab_measurement):
        _translate = QtCore.QCoreApplication.translate
        Lab_measurement.setWindowTitle(_translate("Lab_measurement", "Form"))
        self.Lab_Intro.setHtml(_translate("Lab_measurement", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Вы находитесь на странице вычислений для Лабороторных измерений</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p></body></html>"))
        self.choise_text.setHtml(_translate("Lab_measurement", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Выбирите вид измерения:</span></p></body></html>"))
        self.GKH_btn.setToolTip(_translate("Lab_measurement", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.GKH_btn.setText(_translate("Lab_measurement", "ГХ"))
        self.tilte_btn.setToolTip(_translate("Lab_measurement", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tilte_btn.setText(_translate("Lab_measurement", "метод тильтрования"))
        self.Back_btn.setText(_translate("Lab_measurement", "Back"))

    def back_action(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Lab_measurement = QtWidgets.QWidget()
#     ui = Ui_Lab_measurement()
#     ui.setupUi_lab(Lab_measurement)
#     Lab_measurement.show()
#     sys.exit(app.exec_())
