# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from LabWindow import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setStyleSheet("background-color: rgb(181, 181, 181);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.FieldButton = QtWidgets.QPushButton(self.centralwidget)
        self.FieldButton.setGeometry(QtCore.QRect(80, 280, 261, 181))
        self.FieldButton.setStyleSheet("background-color: rgb(145, 145, 145);")
        self.FieldButton.setObjectName("FieldButton")

        self.LabButton = QtWidgets.QPushButton(self.centralwidget)
        self.LabButton.setGeometry(QtCore.QRect(470, 280, 261, 181))
        self.LabButton.setStyleSheet("background-color: rgb(161, 161, 161);")
        self.LabButton.setObjectName("LabButton")
        self.LabButton.clicked.connect(self.popup_action)

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(100, 40, 611, 151))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FieldButton.setText(_translate("MainWindow", "Полевое измерение"))
        self.LabButton.setText(_translate("MainWindow", "Лаборотоное измерение"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Где было сделано измерение?</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p></body></html>"))

    def popup_action(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Lab_measurement()
        self.ui.setupUi_lab(self.window)
        self.window.show()
